### ISSUE TITLE
Bugs/Add/remove/changes for next release

### ISSUE THREAD

**Issue by calloatti** [AllOfFabric/AOF-Strawberry#1]
Add woodmill

DONE

**Comment by calloatti** [comment]
Add woodmill

Maybe add this https://www.curseforge.com/minecraft/mc-mods/presence-footsteps

**Comment by calloatti** [comment]
Antique Atlas when you change "requiresHold": true to false it renders the map but blank

**Comment by calloatti** [comment]
Make antique Atlas position default to top right instead of top left

**Comment by NinjaPhenix** [comment]
Trees don't float: trigger -> `LOG_BREAK`
Better Sleep: awakeDebuff: `false` (perhaps just increase nightsBeforeDebuff to like a ingame week `7`)

**Comment by NinjaPhenix** [comment]
Possibly add crafting pad: https://www.curseforge.com/minecraft/mc-mods/craftingpad-fabric

**Comment by Gbergz** [comment]
Reset REI config

**Comment by calloatti** [comment]
Tweak disenchanting table LevelMultiplier  5 is too expensive

**Comment by NinjaPhenix** [comment]
Changed to 2.5 on server (testing).

In a `minecraft/loot_tables/blocks/white_wool.json`:

```json
{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:alternatives",
          "children": [
            {
              "type": "minecraft:item",
              "conditions": [
                {
                  "condition": "minecraft:match_tool",
				  "predicate": {
				  "item": "minecraft:shears"
				  }
                }
              ],
			  "functions": [
                {
                  "function": "minecraft:set_count",
                  "count": {
                    "min": 1.0,
                    "max": 4.0,
                    "type": "minecraft:uniform"
                  }
                }
			],
              "name": "minecraft:string"
            },
            {
              "type": "minecraft:item",
              "conditions": [
                {
                  "condition": "minecraft:survives_explosion"
                }
              ],
              "name": "minecraft:white_wool"
            }
          ]
        }
      ]
    }]
}
```

**Comment by calloatti** [comment]
claimchunk default config may have to be adjusted

```
{
  "prevent_using_blocks": true,
  "prevent_using_items": true,
  "prevent_breaking_blocks": true,
  "prevent_building": true,
  "prevent_attacking_entities": true,
  "max_claims": 10
}
```

Maybe enable use items and lower number of chunks

**Comment by NinjaPhenix** [comment]
Add [BigXPOrbs 0.0.2](https://cdn.discordapp.com/attachments/599986064639262721/609800172548915200/Big_XP-0.0.2.jar)

**Comment by Gbergz** [comment]
Remove / disable first person mod by default.

**Comment by NinjaPhenix** [comment]
Add: https://media.forgecdn.net/files/2759/210/FatExperienceOrbs-0.0.2.jar

**Comment by calloatti** [comment]
https://github.com/AllOfFabric/AOF-Strawberry/commit/156e8a368c4813073d22f5b0e3f2e8bcc57444c6
