### ISSUE TITLE
Mod addition suggestions

### ISSUE THREAD

**Issue by Shnupbups** [AllOfFabric/AOF-Strawberry#13]
[Better Wither Skeletons by smushytaco](https://www.curseforge.com/minecraft/mc-mods/better-wither-skeletons)
[Glitter by gudenau](https://www.curseforge.com/minecraft/mc-mods/glitter)
[Just Another Redstone Gate Mod by MarioAndWeegee3](https://www.curseforge.com/minecraft/mc-mods/just-another-redstone-gate-mod)

All are fairly small and vanilla-ish mods that I believe would fit perfectly into the pack.

**Comment by Shnupbups** [comment]
[Golem Healer by Shnupbups](https://www.curseforge.com/minecraft/mc-mods/golem-healer) (that's me!)

**Comment by Shnupbups** [comment]
[Better Compass (Fabric) by Lemonszz and Shnupbups](https://www.curseforge.com/minecraft/mc-mods/better-compass-fabric) (me again!)

**Comment by calloatti** [comment]
Added all of them, if any of the mods is not in the final release, it will be because of problems in testing.
