### ISSUE TITLE
Add default configs mod

### ISSUE THREAD

**Issue by calloatti** [AllOfFabric/AOF-Strawberry#2]
Maybe https://www.curseforge.com/minecraft/mc-mods/randomconfigs

**Comment by Gbergz** [comment]
Change chunkclaim default config to this:
`{
  "prevent_using_blocks": true,
  "prevent_using_items": false,
  "prevent_breaking_blocks": true,
  "prevent_building": true,
  "prevent_attacking_entities": false,
  "max_claims": 115
}`

**Comment by NinjaPhenix** [comment]
If so, please set auto jump to off by default.

**Comment by calloatti** [comment]
Fixed next release. Only on client, crashes on server.
