### ISSUE TITLE
remove mod that lets enchantments stack

### ISSUE THREAD

**Issue by Gbergz** [AllOfFabric/AOF-Strawberry#9]
It doesn't really fit the style of the pack imo. It's really overpowered 

Talking about that you can stack Sharpness V, Smite V, & Bane Of Athropods V, and same with armor
Protection IV, Projectile IV, Blast IV, Fire IV, you kind of become semi-invincible.

Thoughts, calloatti?

**Comment by calloatti** [comment]
You are probably right. Too bad its not configurable to like 2 stacked enchants for example.

**Comment by calloatti** [comment]
Disabled next release
